### ISSUE TITLE
ReferenceError: couldn't resolve escope/referencer

### ISSUE THREAD

**Issue by reznord** [bradleyboy/yarsk#32]
Hello @bradleyboy , thanks for this amazing starter kit. I am developing an application using your starter kit and I am getting the following error while I am trying to run **npm start**

`
➜  analyze git:(master) ✗ npm start

> yarsk@1.0.0 start /Users/anup/projects/analyze
> webpack-dev-server --config conf/webpack.config.js --hot --history-api-fallback --progress --colors --content-base ./build --host 0.0.0.0

  0% compilehttp://0.0.0.0:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/anup/projects/analyze/build
404s will fallback to /index.html
 10% 0/1 build modulesReferenceError: couldn't resolve escope/referencer
    at monkeypatch (/Users/anup/projects/analyze/node_modules/babel-eslint/index.js:85:11)
    at Object.exports.parse (/Users/anup/projects/analyze/node_modules/babel-eslint/index.js:422:5)
    at parse (/Users/anup/projects/analyze/node_modules/eslint/lib/eslint.js:462:27)
    at EventEmitter.module.exports.api.verify (/Users/anup/projects/analyze/node_modules/eslint/lib/eslint.js:614:15)
    at processText (/Users/anup/projects/analyze/node_modules/eslint/lib/cli-engine.js:225:23)
    at CLIEngine.executeOnText (/Users/anup/projects/analyze/node_modules/eslint/lib/cli-engine.js:336:22)
    at lint (/Users/anup/projects/analyze/node_modules/eslint-loader/index.js:17:20)
    at Object.module.exports (/Users/anup/projects/analyze/node_modules/eslint-loader/index.js:80:3)
    at WEBPACK_CORE_LOADER_EXECUTION (/Users/anup/projects/analyze/node_modules/webpack-core/lib/NormalModuleMixin.js:155:71)
    at runSyncOrAsync (/Users/anup/projects/analyze/node_modules/webpack-core/lib/NormalModuleMixin.js:155:93)
    at nextLoader (/Users/anup/projects/analyze/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /Users/anup/projects/analyze/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/Users/anup/projects/analyze/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /Users/anup/projects/analyze/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete](fs.js:445:3)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.3.0/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! yarsk@1.0.0 start: `webpack-dev-server --config conf/webpack.config.js --hot --history-api-fallback --progress --colors --content-base ./build --host 0.0.0.0`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the yarsk@1.0.0 start script 'webpack-dev-server --config conf/webpack.config.js --hot --history-api-fallback --progress --colors --content-base ./build --host 0.0.0.0'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the yarsk package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --config conf/webpack.config.js --hot --history-api-fallback --progress --colors --content-base ./build --host 0.0.0.0
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs yarsk
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls yarsk
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/anup/projects/analyze/npm-debug.log
➜  analyze git:(master) ✗
`

I tried the following steps and I am still not able to find where I am going wrong: 
- removed the node modules and installed them again. 
- rm -rf node_modules && npm cache clean && npm install; 

My configuration and versions of npm:
- npm version: 3.10.3
- nodejs version: 6.3.0
- react version: 15.2.1

Can you help me with the following issue and help me out?

**Comment by reznord** [comment]
Resolved the issue: 

It was some problem with the eslint configuration. I disabled the preloaders in the webpack config and it worked for me. 

Thanks !!
