### ISSUE TITLE
libsass bindings not found

### ISSUE THREAD

**Issue by winkler1** [bradleyboy/yarsk#5]
missing node deps? not a sass user here.

```
$ npm run build

> yarsk@1.0.0 build /Users/Jeff/repos/yarsk
> webpack --config conf/webpack.production.js

Error: `libsass` bindings not found. Try reinstalling `node-sass`?
    at getBinding (/Users/Jeff/repos/yarsk/node_modules/sass-loader/node_modules/node-sass/lib/index.js:22:11)
    at Object.<anonymous> (/Users/Jeff/repos/yarsk/node_modules/sass-loader/node_modules/node-sass/lib/index.js:188:23)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Jeff/repos/yarsk/node_modules/sass-loader/index.js:4:12)
    at Module._compile (module.js:460:26)
```

**Comment by bradleyboy** [comment]
Hate to give you the "It works here" answer again, but...it does. 

node-sass is a dependency of the sass-loader package, so it should be pulled in automatically. Have you tried nuking node_modules and re-running npm install?
